functionSecretConfig:
  debugToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBpZCI6ImwxNjZpbyIsInR5cGUiOiJkZXZlbG9wIiwiZXhwIjoxNjgxOTI3MTIzLCJpYXQiOjE2ODEzMjIzMjN9.xyJIkdDK8JKydnomBLvDM2RgB_k1FuBqgVKFZHS4pEE
  debugTokenExpire: 1681927123
storageSecretConfig:
  endpoint: https://oss.laf.run
  accessKeyId: RHOUTET6E0JPTKQ1S02I
  accessKeySecret: WsA0w4Eppm7G018GME2g7RKbIrkgG3wCXRXbJ4yb
  sessionToken: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJSSE9VVEVUNkUwSlBUS1ExUzAySSIsImV4cCI6MTY4MTkyNzEyMywicGFyZW50IjoibDE2NmlvIiwic2Vzc2lvblBvbGljeSI6ImV5SldaWEp6YVc5dUlqb2lNakF4TWkweE1DMHhOeUlzSWxOMFlYUmxiV1Z1ZENJNlczc2lVMmxrSWpvaVlYQndMWE4wY3kxbWRXeHNMV2R5WVc1MElpd2lSV1ptWldOMElqb2lRV3hzYjNjaUxDSkJZM1JwYjI0aU9pSnpNem9xSWl3aVVtVnpiM1Z5WTJVaU9pSmhjbTQ2WVhkek9uTXpPam82S2lKOVhYMD0ifQ.hNUrA0cScp5Kz6j7pUJRFJbN_A4R8trDdwiR0s-R8bda4aaCe5SBDhGscFGyJnoZzXGB_W5o1CQsi49OB5jQVg
  expire: 1681927123
